### ISSUE TITLE
Some metrics are missing

### ISSUE THREAD

**Issue by mjsjinsu** [cloudfoundry-community/firehose_exporter#11]
Hi
I try to monitoring CF with prometheus-boshrelease
currently I set up cf exporter, firehose exporter

Most metrics are collected with this exporter
but some metric were not show in prometheus DB

Ex)
firehose_counter_event_gorouter_bad_gateways_delta
firehose_counter_event_gorouter_bad_gateways_total
firehose_counter_event_gorouter_rejected_requests_delta
firehose_counter_event_gorouter_rejected_requests_total
firehose_counter_event_bbs_* metrics empty, except two metrics "firehose_counter_event_bbs_request_count_delta", "firehose_counter_event_bbs_request_count_total"

ENV)
cf : 238
diego : 0.1476.0

cf_exporter, version 0.4.3 (branch: master, revision: 9e37d9069bbb87d739d2c326981fed917ec016e4)
build user: root@1d21624
build date: 20170216-02:38:17
go version: go1.7.5

firehose_exporter, version 4.1.0 (branch: master, revision: 95333eab4c8295bf727faa564add32422f5d71c6)
build user: root@387dfcd
build date: 20170216-01:18:51
go version: go1.7.5

**Comment by frodenas** [comment]
Those metrics are only started to be reported by the gorouter when there's a 1st occurrence of that metric. So, if there aren't yet any rejected request or a bad gateway, the gorouter will not report them.

**Comment by mjsjinsu** [comment]
Thank you I can see that clearly
but counter_event bbs metrics not coming yet

What can i do to solve this problem

Shared grafana Dashboard(CF:BBS)
![image](https://cloud.githubusercontent.com/assets/4901749/23127610/03a93a88-f7bf-11e6-857f-c3574466aebd.png)

**Comment by frodenas** [comment]
Do you have any app running? Most of those metrics are related to LRPs, so if you don't have app, then there's no LRP.

**Comment by mjsjinsu** [comment]
Of cource we have running applications   
   
container metrics (cpu/memory/disk) are all work well

**Comment by frodenas** [comment]
Are you able to get any `firehose_counter_event_bbs_convergence_lrp_runs_total` data at the prometheus console?

**Comment by mjsjinsu** [comment]
No .. I didn't see any "firehose_counter_event_bbs_convergence *" metrics
Only metric i can get is "firehose_counter_event_bbs_request_count_total, firehose_counter_event_bbs_request_count_delta"

**Comment by frodenas** [comment]
@mjsjinsu I'm unsure why you don't get those metrics. Theoretically, Diego 0.1476.0 should emit those metrics according to the code (for [etcd](https://github.com/cloudfoundry/bbs/blob/42d531e76830ef8433fe22e57c02e514113a2272/db/etcd/lrp_convergence.go#L20) and [sqldb](https://github.com/cloudfoundry/bbs/blob/42d531e76830ef8433fe22e57c02e514113a2272/db/sqldb/lrp_convergence.go#L19)). Can you check if the the vm that has the `bbs` job has also the `metron_agent` collocated?

**Comment by mjsjinsu** [comment]
@frodenas Yes, i check diego deployment, all deployed status normal 
As you said me, bbs and metron_agent collocated in diego database job 

database_z1/0
|   etcd                                                     | running |         
|   bbs                                                      | running |             
|   consul_agent                                      | running |              
|   metron_agent                                     | running |              

However during reviewing manifest
In the diego manifest I found there is null properties on bbs cert (ca_cert, client_cert, and key )

I think bbs cert key is cause this problem
how about your thinks?

bbs:
        api_location: bbs.service.cf.internal:8889
        ca_cert: nil
        client_cert: nil
        client_key: nil

**Comment by mjsjinsu** [comment]
@frodenas 
I tested in other cloudfoundry platform env with bbs cert key inserted
all metrics are exported normaly and grafana dashboards are good status
Thank you for answer
