### ISSUE TITLE
Question: What's the time range that firehose counter event deltas calculate from?

### ISSUE THREAD

**Issue by davidchua** [cloudfoundry-community/firehose_exporter#12]
Eg. for metrics like: 

`firehose_counter_event_auctioneer_auctioneer_task_auctions_failed_deltas`
`firehose_counter_event_auctioneer_auctioneer_lrps_auctions_failed_deltas`

The value returned, what is the time range that it is comparing to?

**Comment by frodenas** [comment]
I believe it's 30 seconds, you can check when those metrics are emitted at [Cloud Foundry Component Metrics documentation](https://docs.cloudfoundry.org/loggregator/all_metrics.html#auctioneer).
