### ISSUE TITLE
firehose_exporter internal servererror 500 after update to Pivotal RabbitMQ Service 1.8.*

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-community/firehose_exporter#13]
Reported by @Martin612 at https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/66:

Hello,

I'm using the prometheus bosh release in an Pivotal Cloud Foundry environment.

After updating the rabbitmq service tile to 1.8.* I am experiencing an issue with the firehose_exporter.

The update added an additional service broker for dedicated rabbitmq services.
This additional service broker producing following issue in firehose_exporter:

* collected metric firehose_value_metric_p_rabbitmq_log_sender_total_messages_read label:<name:"bosh_deployment" value:"cf-rabbitmq" > label:<name:"bosh_job_id" value:"8daeceac-05cf-4094-a1ab-d9355dac1584" > label:<name:"bosh_job_ip" value:"192.168.17.15" > label:<name:"bosh_job_name" value:"rabbitmq-broker" > label:<name:"environment" value:"P" > label:<name:"origin" value:"p-rabbitmq" > label:<name:"unit" value:"count" > gauge:<value:0 >  has help "Cloud Foundry Firehose 'logSenderTotalMessagesRead' value metric from 'p-rabbitmq'." but should have "Cloud Foundry Firehose 'logSenderTotalMessagesRead' value metric from 'p.rabbitmq'."

Turning off the logs from dedicated rabbitmq service broker fix this issue temporary.

Can you please update the firehose_exporter to consume logs from shared rabbitmq service broker and from dedicated rabbitmq service broker?

**Comment by frodenas** [comment]
The problem here is that the RabbitMQ ODB is using `p.rabbitmq` as the metric's origin, and the shared broker is using `p-rabbitmq`. Both origins are converted to `p_rabbitmq`when constructing the metric's name (because in Prometheus, the metric's name can not contain `.` nor `-`). That's fine, because both metrics are the same metric, so they will share the same name and we will differentiate it via labels. The problem is that a metric can have a single description, so what we get here is 2 samples for the same metric but with a different description (because at the description no conversion is applied to the origin).

This has no easy fix without breaking existing deployments. A simple solution will be converting the origin when building the description (applying the same method we are using for the metric name), but if we do that, we have the risk of breaking existing deployments, because we might already have metrics with a description containing the `-` character at the origin.

I wonder why the RabbitMQ ODB team picked up a different origin's name? Anyway, let me think if I find a solution for this that does not break old deployments.

**Comment by frodenas** [comment]
This has been fixed at [v4.1.1](https://github.com/cloudfoundry-community/firehose_exporter/releases/tag/v4.1.1).

**Comment by dlapiduz** [comment]
@frodenas we had this issue pop up with the Redis tile too now, is there an easy way to fix the description so it differentiates `p-redis` and `p.redis`?

**Comment by dlapiduz** [comment]
Nevermind, we were using a wrong version by mistake. Sorry about that!
