### ISSUE TITLE
Error while reading from the Firehose: Error dialing trafficcontroller server

### ISSUE THREAD

**Issue by bkeelapudi** [cloudfoundry-community/firehose_exporter#14]
I am trying to run the firehose exporter for prometheus and ran in to this issue as seen below:

Error while reading from the Firehose: Error dialing trafficcontroller server: malformed ws or wss URL.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is https                                                                                       ://doppler.system.**.org).  source="firehose_nozzle.go:104"

**Comment by frodenas** [comment]
@bkeelapudi It seems you're using `https` when you specify the `firehose_exporter.doppler.url` flag (`trafficcontroller is https ://doppler.system.**.org`). Can you please check try using `wss://`?

**Comment by bkeelapudi** [comment]
Thanks @frodenas, Now i am getting a websocket bad handshake error. 

 ubuntu@ip-:~/Prometheus/firehose_exporter-4.1.0.linux-amd64$ ./firehose_exporter -uaa.client-id  -uaa.client-secret  -uaa.url https://uaa.system.*.com -skip-ssl-verify -doppler.url wss://doppler.system.*.com
INFO[0000] Starting firehose_exporter (version=4.1.0, branch=master, revision=95333eab4c8295bf727faa564add32422f5d71c6)  source="firehose_exporter.go:244"
INFO[0000] Build context (go=go1.7.5, user=root@387dfcd86a81, date=20170216-01:18:51)  source="firehose_exporter.go:245"
INFO[0000] Listening on :9186                            source="firehose_exporter.go:320"
INFO[0000] Starting Firehose Nozzle...                   source="firehose_nozzle.go:55"
ERRO[0000] Error while reading from the Firehose: Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.system.*.com).  source="firehose_nozzle.go:104"

**Comment by bkeelapudi** [comment]
Missed to add the websocket port 4443 to the URL . Now it works like a charm, Thanks again @frodenas

**Comment by frodenas** [comment]
Glad to hear it worked!
