### ISSUE TITLE
quota metrics always expose zero value

### ISSUE THREAD

**Issue by thomasspatzier** [cloudfoundry-community/firehose_exporter#3]
In our deployment we found that quota metrics (e.g firehose_exporter_container_metric_disk_bytes_quota) always seem to yield value zero. All other metrics seem to work fine.
In Cloud Foundry, we see reasonable data for quota usage, so could it be that something gets lost in the firehose exporter?

**Comment by frodenas** [comment]
@thomasspatzier What version of diego-release are you using? memory and disk quotas started to be reported in [Diego v0.1482.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1482.0) (see this [commit](https://github.com/cloudfoundry/executor/commit/22fd272689ebb57cbd3c28fe68e9ac4f96ddef25)).

I'm able to fetch those metrics using the latest diego release:

<img width="1429" alt="screen shot 2016-10-26 at 18 30 08" src="https://cloud.githubusercontent.com/assets/405846/19735074/533bd6da-9baa-11e6-9cbd-38dfc773961b.png">

**Comment by thomasspatzier** [comment]
Hi @frodenas - thanks for the quick reply. I don't have access to the system right now, so I can't check for the exact version number. I'll check tomorrow morning and post an update.

**Comment by thomasspatzier** [comment]
@frodenas - So I checked our diego version and it's in fact back-level at version 0.1467.6. So looking at the commit you pointed to, we should be fine when we upgrade. I guess you can close this issue. Thanks for your help!

**Comment by frodenas** [comment]
ok, perfect, thanks for checking this.
