### ISSUE TITLE
getting org-level and space-level metrics

### ISSUE THREAD

**Issue by thomasspatzier** [cloudfoundry-community/firehose_exporter#4]
Is it possible to get high-level metrics at org or space level as well, e.g. number of spaces for an org, number of applications per org/space, number of running/stopped/crashed application - basically what ones gets in the PCF UI, but have it available as metrics in prometheus.

We had a look but could not find such metrics. If it's not there yet, is this on the roadmap somewhere, and would others be interested in this.

BTW, if this looks interesting, we can look into adding this ...

**Comment by frodenas** [comment]
This exporter only gets metrics from the [Cloud Foundry Firehose](https://docs.cloudfoundry.org/loggregator/architecture.html#firehose) and transforms them into a Prometheus format. I don't see that those metrics are reported to the Firehose, or at least, I don't see them at the [Cloud Foundry Component Metrics](Cloud Foundry Component Metrics) documentation. 

If you want them to be reported, you should: 
* add those metrics to the appropriate CF component and report them to the Firehose; 
* create a different exporter that reads this information from the appropriate component and report them as a Prometheus metrics.

**Comment by thomasspatzier** [comment]
We were not sure whether this data is reported on the firehose. Thanks for the clarification and the hints. We'll look into this and see how to get the data out.

**Comment by frodenas** [comment]
@thomasspatzier FYI, I started building a [cf_exporter](https://github.com/cloudfoundry-community/cf_exporter) that will return CF administrative information (like orgs, spaces, apps, ...).

**Comment by thomasspatzier** [comment]
@frodenas thanks for the hint. That looks great. I'll have a look and try it out :-)
