### ISSUE TITLE
getting metrics about services in Cloud Foundry

### ISSUE THREAD

**Issue by thomasspatzier** [cloudfoundry-community/firehose_exporter#5]
It would be interesting to get metrics not only per application, but also for services. Is this something in scope and somewhere on the roadmap?

**Comment by frodenas** [comment]
It's up to the service creator to report its own metrics to the [Cloud Foundry Firehose](https://docs.cloudfoundry.org/loggregator/architecture.html#firehose). I know that some services are starting to report metrics, but I don't know the timing/roadmap.

In the meantime, another approach is to use a specific Prometheus collector for that service. For example, the [Prometheus BOSH Release] (https://github.com/cloudfoundry-community/prometheus-boshrelease) ships with collectors for Consul, HAProxy, MySQL, NATS, PostgreSQL, ... so theoretically you can use those collectors to report service metrics.

**Comment by thomasspatzier** [comment]
Oh, I was not thinking about service specific metrics but just the basic that we also get for apps, like cpu percentage, disk bytes, etc. and whether those would be available on the firehose as well. Agreed, everything else should be in different collectors/exporters.

We'll look at Prometheus BOSH Release as you suggested. Thanks!

**Comment by frodenas** [comment]
Well, if you just want to get system level metrics, you can use the [Node exporter](https://github.com/prometheus/node_exporter) or, for basic metrics, the [BOSH exporter](https://github.com/cloudfoundry-community/bosh_exporter). The latter will fetch metrics from the BOSH director for each deployment.
