### ISSUE TITLE
index field from firehose exported as bosh_index instead of bosh_job_id

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry-community/firehose_exporter#7]
Hi,

For an event like that:
origin:"gorouter" eventType:ValueMetric job:"router" index:"b68ad2dc-1755-4588-a2bb-e261ffa251dd"

this exporter will export the index field as bosh_index. Meanwhile, bosh_exporter would export this value as bosh_job_id. This discrepancy prevents joins in Prometheus queries later. Relabelling would be a workaround but I don't think that's necessary - we could just change this exporter to export this field as bosh_job_id instead. Do you agree? I can prepare a PR if you are ok with this change. Thanks.

**Comment by frodenas** [comment]
There are still `metron_agents` that reports the job `index` instead of the `id`, but yeah, it should be fine if we rename the label to use `bosh_job_id`.
